IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_NAME = 'Reservas' AND COLUMN_NAME = 'IngressoId'
)
BEGIN
    ALTER TABLE Reservas ADD IngressoId UNIQUEIDENTIFIER NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';
END

IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_NAME = 'Ingressos' AND COLUMN_NAME = 'DataBloqueio'
)
BEGIN
    ALTER TABLE Ingressos ADD DataBloqueio DATETIME NULL;
END
