-- Script0009: Adicionar colunas Tipo, Descricao, Local, Cancelado a Eventos

IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_NAME = 'Eventos' AND COLUMN_NAME = 'Tipo'
)
BEGIN
    ALTER TABLE dbo.Eventos ADD Tipo INT NOT NULL DEFAULT 0;
END

IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_NAME = 'Eventos' AND COLUMN_NAME = 'Descricao'
)
BEGIN
    ALTER TABLE dbo.Eventos ADD Descricao NVARCHAR(500) NULL;
END

IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_NAME = 'Eventos' AND COLUMN_NAME = 'Local'
)
BEGIN
    ALTER TABLE dbo.Eventos ADD Local NVARCHAR(200) NULL;
END

IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_NAME = 'Eventos' AND COLUMN_NAME = 'Cancelado'
)
BEGIN
    ALTER TABLE dbo.Eventos ADD Cancelado BIT NOT NULL DEFAULT 0;
END
