IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Reservas')
BEGIN
    CREATE TABLE Reservas (
        Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
        UsuarioCpf NVARCHAR(11) NOT NULL,
        EventoId UNIQUEIDENTIFIER NOT NULL,
        IngressoId UNIQUEIDENTIFIER NOT NULL,
        CupomUtilizado NVARCHAR(49),
        ValorFinalPago NUMERIC(10,2) NOT NULL
    );
END