IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Usuarios')
BEGIN
    CREATE TABLE Usuarios (
        Cpf NVARCHAR(11) NOT NULL PRIMARY KEY,
        Nome VARCHAR(100) NOT NULL,
        Email VARCHAR(100) NOT NULL UNIQUE,
        PerfilId UNIQUEIDENTIFIER NOT NULL,
        Senha VARCHAR(100) NOT NULL
    );
END
