IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_NAME = 'Eventos' AND COLUMN_NAME = 'VendedorCpf'
)
BEGIN
    ALTER TABLE dbo.Eventos ADD VendedorCpf NVARCHAR(11) NOT NULL DEFAULT '';
END
