IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_NAME = 'Reservas' AND COLUMN_NAME = 'DataBloqueio'
)
BEGIN
    ALTER TABLE Reservas ADD DataBloqueio DATETIME NOT NULL DEFAULT GETDATE();
END
