IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Eventos')
BEGIN
    CREATE TABLE dbo.Eventos (
        id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
        Nome VARCHAR(100) NOT NULL,
        CapacidadeTotal INT NOT NULL,
        DataEvento DATETIME NOT NULL,
        PrecoPadrao DECIMAL(10,2) NOT NULL
    );
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Ingressos')
BEGIN
    CREATE TABLE dbo.Ingressos (
        Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
        EventoId UNIQUEIDENTIFIER NOT NULL,
        Preco DECIMAL(10,2) NOT NULL,
        Posicao VARCHAR(50) NOT NULL,
        Setor VARCHAR(20) NOT NULL,
        Status INT NOT NULL DEFAULT 0,
        DataBloqueio DATETIME NULL,
        CONSTRAINT FK_Ingressos_Eventos FOREIGN KEY (EventoId) REFERENCES dbo.Eventos(id)
    );
END
